---
## Backup settings

# Minimum no. of days between each instance's backups
# - "Minimum": An instance will only be backed up after min_backup_interval full days has passed, if its container ran during that interval / is currently running
# - All of a container's associated instances will be backed up together to ensure data synchronization
# - Backups are independently conducted for each container ie. a new container being backed up will not cause other existing containers to be backed up
# min_backup_interval: 0

# Max number of days (inclusive) to keep backups of an instance after its container has been deleted
# - Default value of -1 means such backups are never pruned
# ghost_backup_keep_days: -1

# Max number of backups of an instance to keep (whose container is still not deleted)
# - Pruning of extra backups occurs before new ones are created
# - Default value of -1 means extra backups are never pruned
# backup_keep_num: -1

# Warn if difference between newly created backup and pruned size is more than specified amount
# warn_large_backup_mb: 1024

# If True, backup all containers by default, else if True, only those specified in container_paths
# backup_by_default: True

# Dictionary of containers (identified by short_id - first 12 characters), each with a list of paths to backup (see example provided)
# - If backup_by_default=True and a container ID is not listed in container_paths, the entire container's filesystem will be backed up
# - If the list of paths for a container ID is empty, the script will fall back to the backup_by_default when deciding whether the container should be backed up
# - Backups for all specified paths for a container will occur, as long as one of them meets the backup condition / have not been backed up before
# - Removing a specified path will mark that instance as deleted
# container_paths:
  # fd312f3n7h45:
  # - /etc
  # - /home/main.py
  # container_id_2:
  # - /path/to/file
  # - /path/to/dir


## Notification settings

# Chat ID of your telegram account to send notifications to (must be used together with telegram_bot_token)
# telegram_chat_id: TELEGRAM_CHAT_ID

# Bot Token of your telegram bot to send notifications from (must be used together with telegram_chat_id)
# telegram_bot_token: TELEGRAM_BOT_TOKEN


## Paths to directories containing output file (Ensure these are created already)

# Directory containing instance_info.csv, a persistent file that stores metadata about each instance and its backups
# instance_info_dir_path: C:\Path\to\current\directory

# Directory containing backups
# backup_dir_path: C:\Path\to\your\container\backups

# Directory containing log files of backups
# log_dir_path: C:\Path\to\your\container\logs